version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit_message:
      prefix: "chore"
      include_scope: true
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/"
    commit_message:
      prefix: "chore"
      include_scope: true
    schedule:
      interval: "weekly"
    reviewers:
      - "devcyclehq/engineering"
